version: '3'

services:
  web:
    image: tomcat:latest
    ports:
      - "80:8080"
    volumes:
      - ./target/:/usr/local/tomcat/webapps/
    links:
      - db
  db:
    image: mysql:5.7
    ports:
      - '3306:3306'
    volumes:
      - ./mysql-data/:/var/lib/mysql
      - ./mysql-init-files:/docker-entrypoint-initdb.d
    environment:
      MYSQL_DATABASE: "ebookshop"
      MYSQL_USER: "java"
      MYSQL_PASSWORD: "3kla912kj"
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_ALLOW_EMPTY_PASSWORD: "no"
volumes:
  my-db:
